// Importing necessary functions from Redux Toolkit
import { createSlice, nanoid } from '@reduxjs/toolkit'

// Initial state for the todo slice
const initialState = {
    todos: []
}

// Creating a todo slice using createSlice function from Redux Toolkit
export const todoSlice = createSlice({
    name: 'todo', // Name of the slice
    initialState, // Initial state
    reducers: {
        // Reducer function to add a new todo item
        addTodo: (state, action) => {
            // Generating a unique id for the new todo using nanoid function
            const todo = {
                id: nanoid(), // Unique id
                text: action.payload // Text of the todo, obtained from action payload
            }
            // Adding the new todo to the state's todos array
            state.todos.push(todo)
        },
        // Reducer function to remove a todo item
        removeTodo: (state, action) => {
            // Filtering out the todo with the id provided in the action payload
            state.todos = state.todos.filter((todo) => todo.id !== action.payload)
        }
    }
})

// Exporting the action creators generated by createSlice
export const { addTodo, removeTodo } = todoSlice.actions

// Exporting the reducer function generated by createSlice
export default todoSlice.reducer
